import { TeamRoster } from './types';

export const jvRoster: TeamRoster = {
  players: [
    { number: '00', name: 'Marcus Dickherber', year: 'Jr.', positions: ['GK'], height: '5\'10"', weight: '160 lbs' },
    { number: '1', name: 'Rogerio Alves', year: 'Fr.', positions: ['D'], height: '5\'7"', weight: '130 lbs' },
    { number: '2', name: 'Matheus Araujo', year: 'Fr.', positions: ['MF', 'FORW'], height: '5\'7"', weight: '108 lbs' },
    { number: '3', name: 'Weston Christensen', year: 'Fr.', positions: ['MF'], height: '5\'5"', weight: '100 lbs' },
    { number: '4', name: 'Ruben Cortes-Mendoza', year: 'Fr.', positions: ['FB'], height: '5\'6"', weight: '145 lbs' },
    { number: '5', name: 'Davi Fernandes', year: 'Fr.', positions: ['MF'], height: '5\'7"', weight: '128 lbs' },
    { number: '6', name: 'Cavner Foster', year: 'Fr.', positions: ['D'], height: '5\'11"', weight: '125 lbs' },
    { number: '7', name: 'Nico Garcia', year: 'So.', positions: ['MF', 'FORW'], height: '5\'8"', weight: '137 lbs' },
    { number: '8', name: 'Chris Maldonado', year: 'So.', positions: ['FORW'], height: '-', weight: '-' },
    { number: '9', name: 'James Ku', year: 'Fr.', positions: ['D'], height: '5\'3"', weight: '110 lbs' },
    { number: '10', name: 'Emerson Meade', year: 'So.', positions: ['FORW', 'FB'], height: '6\'0"', weight: '155 lbs' },
    { number: '11', name: 'AJ Medrano', year: 'Jr.', positions: ['MF'], height: '5\'7"', weight: '135 lbs' },
    { number: '12', name: 'Jonathan Nguyen', year: 'Fr.', positions: ['MF'], height: '5\'6"', weight: '110 lbs' },
    { number: '13', name: 'Bernardo Pinto', year: 'Fr.', positions: ['FB'], height: '5\'6"', weight: '126 lbs' },
    { number: '14', name: 'Adrian Resendiz', year: 'So.', positions: ['FB', 'MF'], height: '5\'6"', weight: '129 lbs' },
    { number: '15', name: 'Alexandru Tapu', year: 'So.', positions: ['FB'], height: '5\'10"', weight: '145 lbs' },
    { number: '16', name: 'Gustavo Teixeira', year: 'Fr.', positions: ['MF', 'FORW'], height: '5\'8"', weight: '120 lbs' },
    { number: '18', name: 'Eli Humphries', year: 'Fr.', positions: ['FORW', 'STRK'], height: '5\'9"', weight: '130 lbs' },
    { number: '19', name: 'Pablo Anjos', year: 'Jr.', positions: ['MF', 'FORW', 'FB'], height: '5\'9"', weight: '140 lbs' },
    { number: '20', name: 'Felipe Silva', year: 'Jr.', positions: ['FORW', 'MF'], height: '5\'3"', weight: '119 lbs' },
    { number: '21', name: 'Alexander Elchaer', year: 'Jr.', positions: ['FB', 'FORW'], height: '5\'8"', weight: '170 lbs' },
    { number: '22', name: 'Naizir Fernandes', year: 'So.', positions: ['FB'], height: '5\'10"', weight: '170 lbs' },
    { number: '23', name: 'Enzo Kukreja', year: 'So.', positions: ['MF'], height: '5\'9"', weight: '130 lbs' },
    { number: '25', name: 'Arpit Ramani', year: 'Jr.', positions: ['FB', 'STRK'], height: '5\'10"', weight: '150 lbs' },
    { number: '66', name: 'Reggie Garcia', year: 'So.', positions: ['GK'], height: '6\'0"', weight: '250 lbs' },
    { number: '77', name: 'Benjamin Gloria', year: 'Fr.', positions: ['GK'], height: '5\'9"', weight: '140 lbs' },
    { number: '98', name: 'Isaac Spengler', year: 'Fr.', positions: ['GK'], height: '5\'6"', weight: '120 lbs' },
    { number: '99', name: 'George Campbell', year: 'So.', positions: ['GK'], height: '6\'4"', weight: '175 lbs' },
  ],
  staff: [
    { name: 'Ariel Medrano', position: 'Statistician' },
    { name: 'Paul Chance', position: 'Head Coach' },
    { name: 'Melissa Rogers', position: 'Head Coach' },
    { name: 'Zac Adkins', position: 'Community Coach' },
  ],
};

export const varsityRoster: TeamRoster = {
  players: [
    { number: '00', name: 'Marcus Dickherber', year: 'Jr.', positions: ['GK'], height: '5\'10"', weight: '160 lbs' },
    { number: '1', name: 'Max Garrett', year: 'Sr.', positions: ['D'], height: '5\'10"', weight: '-' },
    { number: '2', name: 'Greyson Arrigo', year: 'So.', positions: ['MF', 'FORW', 'D'], height: '5\'10"', weight: '140 lbs' },
    { number: '3', name: 'Alberto Hernandez-Ojeda', year: 'Sr.', positions: ['D', 'MF'], height: '5\'10"', weight: '183 lbs' },
    { number: '4', name: 'Manny Adetona', year: 'Sr.', positions: ['D'], height: '5\'9"', weight: '166 lbs' },
    { number: '5', name: 'JP Goncalves', year: 'Sr.', positions: ['FB', 'MF', 'STRK'], height: '6\'2"', weight: '171 lbs' },
    { number: '6', name: 'Michael Giwa', year: 'Fr.', positions: ['FB', 'STRK'], height: '5\'9"', weight: '140 lbs' },
    { number: '7', name: 'Fredrick Sandre', year: 'Fr.', positions: ['MF', 'STRK'], height: '5\'10"', weight: '155 lbs' },
    { number: '8', name: 'Roman Hakim', year: 'Jr.', positions: ['STRK', 'MF'], height: '5\'1"', weight: '95 lbs' },
    { number: '9', name: 'Vinicius Ribeiro', year: 'Sr.', positions: ['STRK'], height: '5\'9"', weight: '178 lbs' },
    { number: '10', name: 'Rafael Lima', year: 'Sr.', positions: ['STRK', 'MF'], height: '5\'9"', weight: '135 lbs' },
    { number: '11', name: 'Arthur Pimentel', year: 'Jr.', positions: ['MF', 'D'], height: '6\'1"', weight: '180 lbs' },
    { number: '12', name: 'Abraham Merhai', year: 'So.', positions: ['MF'], height: '5\'11"', weight: '140 lbs' },
    { number: '13', name: 'Davis Marshall', year: 'Sr.', positions: ['D', 'FB'], height: '5\'9"', weight: '155 lbs' },
    { number: '14', name: 'Gabriel Ribeiro', year: 'Sr.', positions: ['STRK'], height: '6\'1"', weight: '160 lbs' },
    { number: '15', name: 'Nathan Cheplak', year: 'Jr.', positions: ['MF'], height: '5\'8"', weight: '135 lbs' },
    { number: '16', name: 'Luis Betancourt', year: 'Sr.', positions: ['D'], height: '5\'7"', weight: '121 lbs' },
    { number: '17', name: 'Brendan Banks', year: 'Fr.', positions: ['MF', 'FORW'], height: '5\'10"', weight: '145 lbs' },
    { number: '19', name: 'Pablo Anjos', year: 'Jr.', positions: ['MF', 'STRK'], height: '5\'9"', weight: '140 lbs' },
    { number: '21', name: 'Alexander Elchaer', year: 'Jr.', positions: ['FB', 'STRK'], height: '5\'8"', weight: '170 lbs' },
    { number: '22', name: 'Naizir Fernandes', year: 'So.', positions: ['FB'], height: '5\'10"', weight: '-' },
    { number: '23', name: 'Enzo Kukreja', year: 'So.', positions: ['MF'], height: '5\'9"', weight: '130 lbs' },
    { number: '24', name: 'Oliver Jones', year: 'Jr.', positions: ['D'], height: '6\'1"', weight: '175 lbs' },
    { number: '25', name: 'Arpit Ramani', year: 'Jr.', positions: ['FB', 'STRK'], height: '5\'10"', weight: '150 lbs' },
    { number: '66', name: 'Reggie Garcia', year: 'So.', positions: ['GK'], height: '6\'0"', weight: '250 lbs' },
    { number: '77', name: 'Benjamin Gloria', year: 'Fr.', positions: ['GK'], height: '5\'9"', weight: '140 lbs' },
    { number: '99', name: 'George Campbell', year: 'So.', positions: ['GK'], height: '6\'4"', weight: '175 lbs' },
  ],
  staff: [
    { name: 'Ariel Medrano', position: 'Statistician' },
    { name: 'Paul Chance', position: 'Head Coach' },
    { name: 'Melissa Rogers', position: 'Head Coach' },
    { name: 'Zac Adkins', position: 'Community Coach' },
  ],
}; 